on: push
name: Pokemon Worflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
  jasmine-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependancies
        run: npm ci
      - name: Test UT
        run: npm run test:ci
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependancies
        run: npm ci
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          command: yarn cypress run --headed --browser chrome


