on: push
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependancies
        run: npm i
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
  jasmine-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependancies
        run: npm i
      - name: Test UT
        run: npm run test:ci
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependancies
        run: npm i
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
